### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by acelaya** [nikolaposa/cascader#7]
Hey!

I was creating a PR here to add support for PHP 8 on the project, in preparation to do the same on `nikolaposa/monolog-factory`, but I see this project has a dev dependency on `php-cs-fixer`, which does not support PHP 8 and doesn't seem to be something close in time.

Since you just seem to be checking styles against PSR-2, would you be open to change it by `PHP_CodeSniffer` which already supports PHP8?

**Comment by nikolaposa** [comment]
Hm, perhaps I can simply replace `php-cs-fixer` dependency for a binary. I'll think about it these days, I'll consider `PHP_CodeSniffer` as well.

**Comment by acelaya** [comment]
I tried doing an install with --ignore-platform-reqs, but then the tool was still checking the PHP version and failing at runtime, so I don't know if replacing it with a binary would solve the problem.

**Comment by nikolaposa** [comment]
What I meant is:
1. remove CS Fixer dev dependncy entirely
2. download binary of a fixed CS Fixer version
3. put binary under version control
4. optionally change aliases in composer.json (if they exist) to use this binary 

I don't like the fact that this approach implies putting 3rd party tool under version control, but I've seen some projects doing this for PHPUnit as well.

**Comment by nikolaposa** [comment]
I remember this interesting discussion on the subject: https://twitter.com/infection_php/status/969453737428357121.

**Comment by acelaya** [comment]
Oh, yeah, I think I understood it, but I didn't notice the cs checks are done only in one PHP version, which allows doing it in the smallest supported version only, so that approach would work :slightly_smiling_face:

**Comment by acelaya** [comment]
Hey!

I was revisiting this and I saw you already created this PR to add PHP8 support to another package https://github.com/nikolaposa/version/pull/34/files

Do you want me to contribute pull requests to this project to:
* Move from Travis to github actions, adding PHP 7.3 and 7.4 support in the process. I can use the workflow from nikolaposa/version as template for this repo.
* Once that is merged, add PHP 8 support to this project, using the same approach you used on versions one.

I can also do the same on the monolog-factory package, if you are ok with it.

**Comment by nikolaposa** [comment]
Migrating from Travis to GitHub Actions would be amazing. 🙏🏻 

As for PHP CS Fixer issues, I'm still having a dilemma what to do about dev dependencies in general, but I think we can now simply update it to a new version, as it seems that they've finally added PHP 8 support: https://github.com/ergebnis/php-cs-fixer-config/pull/265.

I look forward to your contributions, thank you!

**Comment by acelaya** [comment]
> I think we can now simply update it to a new version, as it seems that they've finally added PHP 8 support: ergebnis/php-cs-fixer-config#265.

That simplifies things a lot 🙂 

I'll start with the first PR then 💪🏼

**Comment by acelaya** [comment]
I have just created the PR that adds Github Actions and support for PHP 8.

I have also removed support for PHP 7.0 and 7.1, which is something that we didn't discuss. If you want to keep support for those versions, let me know and I'll try to get it back.

BTW, I'm not sure why, but the workflow is not getting run. Maybe it doesn't work until it is merged? 🤔

**Comment by nikolaposa** [comment]
> I'm not sure why, but the workflow is not getting run. Maybe it doesn't work until it is merged? 

Yep, I believe that's the case.

**Comment by acelaya** [comment]
I have just created the second PR that bumps dependencies https://github.com/nikolaposa/cascader/pull/9

Having Github Actions simplifies the process 🙂
